[package]
name = "warshall-floyd-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6"
nalgebra = "0.32"
ndarray = "0.15"
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "warshall_floyd"
harness = false
